### ISSUE TITLE
Roles can be deleted even if they are associate to a workflow

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1464]
1. I create a new status in the orchestra back-office
2. I create a new role depending on this new status
3. I use the new role in a existent Workflow : validator

4. I want to remove this new status, I cannot : OK it's associate to a role
5. I want to remove the new role : I can
6. I want to remove the new status: I can
7. I want to edit the "validator" workflow : I cannot, an error appear.

**Comment by alavieille** [comment]
This is fixed in this PR :

https://github.com/open-orchestra/open-orchestra-user-bundle/pull/94
https://github.com/open-orchestra/open-orchestra-model-interface/pull/171
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/92
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1530
