### ISSUE TITLE
Date picker do not work with firefox

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-cms-bundle#1506]
In OO 1.1.0-ALPHA4

When i use open_orchestra_backoffice.field_types.date, with option widget: single_text, datepicker won't work with firefox (I have firefox 39 ).
It's ok with Chrome.

**Comment by itkg-nanne** [comment]
Fixed in ALPHA5.
Chrome natively comes with a datepicker without any js. FF don't.
To ensure both browsers getting this functionality, we added a css class datepicker.
It could be seen here : https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/v1.1.0-alpha4/BackofficeBundle/Resources/views/Form/form_div_layout.html.twig Line 191
You must be sure to use oo_date_picker with open_orchestra_backoffice.form.field_type.custom_type.date (https://github.com/open-orchestra/open-orchestra-cms-bundle/blob/v1.1.0-alpha4/BackofficeBundle/Resources/config/field_type.yml Line 120)
You should find the css class in generated HTML.

@glenouvel
