### ISSUE TITLE
CSRF invalid token on content form

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-cms-bundle#1543]
Sometimes when we change the status of a content we have an invalid CSRF token. When the error appear there is not the usual red popin but the content form with no CSS. 
![bo_sauvegarde contenu](https://cloud.githubusercontent.com/assets/5470027/14244530/dad554cc-fa5b-11e5-940b-ef30f8bce18c.png)

Could you determine why we have this error? Could you fixed it?

**Comment by itkg-ngilain** [comment]
@itkg-mraiffe : is this PR still releavant ?

**Comment by itkg-canne** [comment]
@itkg-ngilain Maybe it is not the only case, but this happens when a javascript error is triggered when form is submitted. In my case, it was an error on TinyMCE component (the case was fixed : https://github.com/open-orchestra/open-orchestra-cms-bundle/issues/1604 ).
Maybe form submission code should be more defensive and used some try/catch to display an error to the user that is more relevant.

**Comment by itkg-ngilain** [comment]
The description of your issue lacks some important information:
1/ Is it a Back Office or Front Office issue ?
2/ What is the Open Orchestra version used ?

Thank you for your answer.

**Comment by itkg-canne** [comment]
It is in the BO, with OO 1.1.0.

**Comment by itkg-nanne** [comment]
We will catch the js break by adding a data-action to the form to replace the action attr. @itkg-canne

**Comment by itkg-mraiffe** [comment]
When this error append all user data are lost. This make this issue more important. Could you add a fix in 1.1.2?

**Comment by itkg-nanne** [comment]
fixed by :
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1660
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1670
