### ISSUE TITLE
Unable to set access type to inherit when editing a group linked to a site different than current site

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-cms-bundle#1699]
Setting `access_type` to inherit on a node in "group/node role" edition form fails if node is not linked to "current site".

To reproduce :
 - create a site "S1",
 - create a node "N" on site "S1",
 - create a group "G" linked to a site "S1",
 - create a site "S2",
 - set site "S2" as current site (in header bar),
 - edit "group/node roles" for group "G",
 - defines any role with "refused" access type on node "N" and then define it as "inherit".

-> It fails.

Problem is that the `NodeGroupRoleTransformer` uses the current site manager to retrieve parent access type.
```
    protected function isParentAccessGranted(GroupInterface $group, FacadeInterface $facade)
    {
        $siteId = $this->currentSiteManager->getCurrentSiteId();
        $language = $this->currentSiteManager->getCurrentSiteDefaultLanguage();
        $node = $this->nodeRepository->findInLastVersion($facade->modelId, $language, $siteId);
        $parentAccess = $group->getModelGroupRoleByTypeAndIdAndRole(NodeInterface::GROUP_ROLE_TYPE, $node->getParentId(), $facade->name);
        return $parentAccess->isGranted();
    }
```

**Comment by itkg-ngilain** [comment]
Hi this is fixed in 1.1 and 1.2:
https://github.com/open-orchestra/open-orchestra-model-interface/pull/193
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/592
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1741

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1738
https://github.com/open-orchestra/open-orchestra-model-interface/pull/191
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/591
